from dataclasses import dataclass
from datetime import datetime
from typing import Any, Dict, Optional
from abc import ABC


@dataclass
class Event(ABC):
    """Base event class for all events in the system."""
    timestamp: datetime
    source: str

    def __post_init__(self):
        if not self.timestamp:
            self.timestamp = datetime.now()


@dataclass
class QuoteEvent(Event):
    """Simplified quote event for basic market data."""
    instrument: str  
    name: str       # Symbol name
    ltp: float      # Last Traded Price
    ltq: float      # Last Traded Quantity

    def __post_init__(self):
        super().__post_init__()
        


@dataclass
class FullQuoteEvent(Event):
    """Full quote event containing raw exchange data for database storage."""
    instrument: str
    name: str
    raw_data: Dict[str, Any]  # Complete raw data from exchange
    
    def __post_init__(self):
        super().__post_init__()
        if not self.raw_data:
            raise ValueError("Raw data cannot be empty")


@dataclass
class CandleGenerated(Event):
    """Candle generated by CandleMaker."""
    symbol: str
    timeframe: str
    open: float
    high: float
    low: float
    close: float
    volume: int
    vwap: float
    timestamp: datetime
    is_complete: bool = True



@dataclass
class OrderEvent(Event):
    """ Order execution event, sent for entry and exit. BUY OR SELL"""
    order_id: str
    instrument: str
    side: str # 'BUY' or 'SELL'
    price: float # although market order when placed execution will not matter, in logger this can be saved
    strategy: str
    type: str # ENTRY OR EXIT
    candle: CandleGenerated = None
    meta_info: Any = None

@dataclass
class EntrySignal(Event):
    """Entry signal generated by a strategy."""
    symbol: str
    direction: str  # 'BUY' or 'SELL'
    price: float
    strategy: str
    reason: str = ""
    candle: CandleGenerated = None
