from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Dict, Optional
from abc import ABC
import inspect


@dataclass
class Event(ABC):
    """Base event class for all events in the system."""
    timestamp: datetime
    source: str 
    # failong cause arguments follows
    # = field(default_factory=lambda: Event._get_caller_name())
    
    # @staticmethod
    # def _get_caller_name() -> str:
    #     """Returns the name of the function or method that created this event."""
    #     stack = inspect.stack()
    #     # stack[0] is _get_caller_name
    #     # stack[1] is the lambda (default_factory)
    #     # stack[2] is the constructor (__init__) of the dataclass
    #     # stack[3] is the function that actually instantiated the object
    #     if len(stack) > 3:
    #         frame = stack[3]
    #         return frame.function
    #     return "unknown"
    
    def __post_init__(self):
        if not self.timestamp:
            self.timestamp = datetime.now()


@dataclass
class QuoteEvent(Event):
    """Simplified quote event for basic market data."""
    instrument: str  
    name: str       # Symbol name
    ltp: float      # Last Traded Price
    ltq: float      # Last Traded Quantity

    def __post_init__(self):
        super().__post_init__()
        


@dataclass
class FullQuoteEvent(Event):
    """Full quote event containing raw exchange data for database storage."""
    instrument: str
    name: str
    raw_data: Dict[str, Any]  # Complete raw data from exchange
    
    def __post_init__(self):
        super().__post_init__()
        if not self.raw_data:
            raise ValueError("Raw data cannot be empty")


@dataclass
class CandleGenerated(Event):
    """Candle generated by CandleMaker."""
    symbol: str
    timeframe: str
    open: float
    high: float
    low: float
    close: float
    volume: int
    vwap: float
    timestamp: datetime
    is_complete: bool = True



@dataclass
class OrderEvent(Event):
    """ Order execution event, sent for entry and exit. BUY OR SELL"""
    order_id: str
    instrument: str
    side: str # 'BUY' or 'SELL'
    price: float # although market order when placed execution will not matter, in logger this can be saved
    strategy: str
    type: str # ENTRY OR EXIT
    candle: CandleGenerated = None
    meta_info: str = ""
    
# not in use, if used to be updated with OrderEvent
@dataclass
class EntrySignal(Event):
    """Entry signal generated by strategy."""
    symbol: str
    direction: str  # 'BUY' or 'SELL'
    price: float
    strategy: str
    reason: str = ""
    candle: CandleGenerated = None


# not in use, to use OrderEvent instead
@dataclass  
class ExitSignal(Event):
    """Exit signal generated by strategy."""
    symbol: str
    direction: str  # 'BUY' or 'SELL' 
    price: float
    quantity: int
    exit_type: str = "PROFIT"  # "PROFIT", "LOSS", "TIME"
    reason: str = ""


@dataclass
class OrderExecuted(Event):
    """Event fired when an order is executed."""
    symbol: str
    side: str
    price: float
    quantity: int
    order_id: str
    execution_type: str  # 'ENTRY' or 'EXIT'


@dataclass
class PositionUpdate(Event):
    """Event fired when position is updated."""
    symbol: str
    position_size: int
    avg_price: float
    unrealized_pnl: float
    realized_pnl: float


@dataclass
class MarketDataUpdate(Event):
    """Event fired for general market data updates."""
    symbol: str
    data_type: str
    data: Dict[str, Any]
